name: webview
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.8
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  firebase_core: ^2.28.0
  firebase_auth: ^4.15.3
  google_sign_in: ^5.4.3
  flutter_facebook_auth: ^5.0.6
  provider: ^6.0.2
  new_gradient_app_bar: ^0.2.0
  circular_profile_avatar: ^2.0.5
  badges: ^2.0.3
  firebase_messaging: ^14.0.0
  intro_slider: ^4.2.5
  dio: ^5.8.0+1
  flutter_inappwebview: ^5.7.1
  dots_indicator: ^4.0.1
  shrink_sidemenu: ^2.0.0+2
  salomon_bottom_bar: ^3.3.0
  intl_phone_field: ^3.1.0
  awesome_dialog: ^3.2.1
  url_launcher: ^6.1.5
  google_mobile_ads: ^5.0.0
  flutter_advanced_drawer: ^1.3.2
  webview_cookie_manager: ^2.0.6
  sign_in_with_apple: ^5.0.0
  easy_localization: ^3.0.1
  flutter_arc_speed_dial: ^2.0.0
  fluttertoast: ^8.0.9
  onesignal_flutter: ^5.3.4
  permission_handler: ^11.3.0
  flutter_downloader: ^1.8.4
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/introduction_page_images/
    - assets/images/splash_screen_images/
    - assets/images/login_page_images/
    - assets/images/verify_phone_number_pages_images/
    - assets/images/home_page_images/
    - assets/images/
    - assets/translations/
